// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPK_MtdZzuFirvvDhK5PZjqfLYeJxTU28',
    appId: '1:340532532068:web:e40056ecb26100ede1a071',
    messagingSenderId: '340532532068',
    projectId: 'ownproject-f7750',
    authDomain: 'ownproject-f7750.firebaseapp.com',
    storageBucket: 'ownproject-f7750.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhF1T6uoyYQkagI5fCP4vPpcqXPQfDdg',
    appId: '1:340532532068:android:3445d953003e4daee1a071',
    messagingSenderId: '340532532068',
    projectId: 'ownproject-f7750',
    storageBucket: 'ownproject-f7750.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4JQ-zaJBzijFG4dUICdRs32y5U4QCgc',
    appId: '1:340532532068:ios:4e5ea39eff12d101e1a071',
    messagingSenderId: '340532532068',
    projectId: 'ownproject-f7750',
    storageBucket: 'ownproject-f7750.appspot.com',
    iosBundleId: 'com.example.tech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw4JQ-zaJBzijFG4dUICdRs32y5U4QCgc',
    appId: '1:340532532068:ios:4e5ea39eff12d101e1a071',
    messagingSenderId: '340532532068',
    projectId: 'ownproject-f7750',
    storageBucket: 'ownproject-f7750.appspot.com',
    iosBundleId: 'com.example.tech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPK_MtdZzuFirvvDhK5PZjqfLYeJxTU28',
    appId: '1:340532532068:web:bcd2be4df5a9de83e1a071',
    messagingSenderId: '340532532068',
    projectId: 'ownproject-f7750',
    authDomain: 'ownproject-f7750.firebaseapp.com',
    storageBucket: 'ownproject-f7750.appspot.com',
  );
}
